import { RegistrationEntity } from '@/domain/types';

export const mockRegistrations: RegistrationEntity[] = [
  {
    id: 'reg-001',
    eventId: 'evt-mtu-001',
    firstName: 'Alex',
    lastName: 'Johnson',
    email: 'ajohnson@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Senior',
    major: 'Computer Science',
    linkedin: 'linkedin.com/in/alexjohnson',
    status: 'pending',
    createdAt: '2026-09-10T14:32:00Z',
  },
  {
    id: 'reg-002',
    eventId: 'evt-mtu-001',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'mgarcia@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Junior',
    major: 'Electrical Engineering',
    status: 'approved',
    createdAt: '2026-09-11T09:15:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'reg-003',
    eventId: 'evt-mtu-001',
    firstName: 'David',
    lastName: 'Kim',
    email: 'dkim@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Senior',
    major: 'Mechanical Engineering',
    linkedin: 'linkedin.com/in/davidkim',
    status: 'approved',
    createdAt: '2026-09-12T11:00:00Z',
    updatedAt: '2026-09-13T08:30:00Z',
  },
  {
    id: 'reg-004',
    eventId: 'evt-mtu-001',
    firstName: 'Aisha',
    lastName: 'Okonkwo',
    email: 'aokonkwo@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Graduate',
    major: 'Data Science',
    status: 'pending',
    createdAt: '2026-09-13T16:45:00Z',
  },
  {
    id: 'reg-005',
    eventId: 'evt-mtu-001',
    firstName: 'Ryan',
    lastName: 'Torres',
    email: 'rtorres@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Sophomore',
    major: 'Computer Engineering',
    status: 'rejected',
    createdAt: '2026-09-14T10:20:00Z',
    updatedAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'reg-006',
    eventId: 'evt-mtu-001',
    firstName: 'Sophie',
    lastName: 'Nguyen',
    email: 'snguyen@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Senior',
    major: 'Civil Engineering',
    status: 'pending',
    createdAt: '2026-09-15T13:10:00Z',
  },
  {
    id: 'reg-007',
    eventId: 'evt-mtu-001',
    firstName: 'Marcus',
    lastName: 'Williams',
    email: 'mwilliams@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Junior',
    major: 'Chemical Engineering',
    linkedin: 'linkedin.com/in/marcuswilliams',
    status: 'approved',
    createdAt: '2026-09-16T08:00:00Z',
    updatedAt: '2026-09-17T10:15:00Z',
  },
  {
    id: 'reg-008',
    eventId: 'evt-mtu-001',
    firstName: 'Emma',
    lastName: 'Johansson',
    email: 'ejohansson@mtu.edu',
    organization: 'Michigan Technological University',
    year: 'Graduate',
    major: 'Biomedical Engineering',
    status: 'pending',
    createdAt: '2026-09-17T15:30:00Z',
  },
];
